アクショングループのリスト表示に時間が掛かることを追記
algyan/touch_and_try-ReButton pull request #36
Opened 2019-05-23 05:48 UTC by greennote

アクショングループを作成した後、Azure Action Monitorグループの設定画面に反映されるまでには少し時間が掛かる。作成失敗と勘違いしないよう、リストが表示されない場合はすこし待つように記述したらどうか。

2019-05-23 08:49 UTC, matsujirushi commented
わたしの環境だと、そういう事象は無かったです。
@y-ohe さん、どうですか？

2019-05-23 09:20 UTC, y-ohe commented
@matsujirushi @greennote 
「少し時間が掛かる」というのが、どの程度かにもよりますが、私のところで試すと「数秒」ですね。
(Azureのサービス構築としては、たいして長い方ではないですね。)
ネットの環境やタイミング的な問題かも。

2019-05-23 10:02 UTC, y-ohe requested changes
１文追記はOKですが、改行して引用表記の方が良いと思います。

2019-05-24 01:18 UTC, greennote commented
改行して引用文にしておきました。

2019-05-25 01:44 UTC, merged